name: 'twdps-lab Github hosted runner setup action'
description: 'Example team hosted runner configuration action'
inputs:
  working-directory:
    description: set working directory; default is .
    required: false
    default: '.'
  install-secrethub:
    description: install current release version of secrethub
    required: false
    default: 'false'
  install-aws-cli:
    description: install current release version of aws-cli
    required: false
    default: 'false'
  install-awspec:
    description: install current release version of awspec
    required: false
    default: 'false'
  install-kubectl:
    description: install current release version of kubectl
    required: false
    default: 'false'
  install-helm:
    description: install current release version of helm
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: install-secrethub
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-secrethub }}" == "true" ]]; then
          sudo bash -c "curl https://apt.secrethub.io | bash"
          secrethub --version
        fi
    - name: install-aws-cli
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.iinstall-aws-cli }}" == "true" ]]; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi
    - name: install-awspec
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-awspec }}" == "true" ]]; then
          sudo gem install awspec --no-document
          awspec --version
        fi
    - name: install-kubectl
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-kubectl }}" == "true" ]]; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
        fi
    - name: install-helm
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-helm }}" == "true" ]]; then
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          sudo bash -c "./get_helm.sh"
          helm --version
        fi
