name: 'twdps-lab Github hosted runner setup action'
description: 'Example team hosted runner configuration action'
inputs:
  working-directory:
    description: set working directory; default is .
    required: false
    default: '.'
  install-secrethub:
    description: install current release version of secrethub
    required: false
    default: 'false'
  install-awspec:
    description: install current release version of awspec
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: install-secrethub
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-secrethub }}" == "true" ]]; then
          sudo bash -c "curl https://apt.secrethub.io | bash"
          secrethub --version
        fi
    - name: install-awspec
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ "${{ inputs.install-awspec }}" == "true" ]]; then
          sudo gem install awspec
          awspec --version
        fi
        